### ISSUE TITLE
Bug: scrollbar causing layout shift

### ISSUE THREAD

**Issue by jeanlucaslima** [kevinzunigacuellar/web#104]
Here's the buggy behavior: 

https://github.com/kevinzunigacuellar/web/assets/1311402/d8883509-0357-4759-9e8d-6a60d3f34916

I already sent a solution through #103

**Comment by kevinzunigacuellar** [comment]
I am having some trouble reproducing this bug. I tried both windows and mac using chrome (and safari) and it seems that both of them set a space for the scroll bar. Windows has a visible gutter and mac becomes visible on scroll.

I appreciate the help! if you can provide more details

**Comment by jeanlucaslima** [comment]
@kevinzunigacuellar Oh, that's simple: to reproduce it you need to have a tall window or a page without a lot of content. 

If you create a page with the header and footer only you will be able to see that happening.

**Comment by jeanlucaslima** [comment]
I only happened to notice because I do programming on a large screen and I was checking your website after seeing it on Astro's Discord. 😅
