### ISSUE TITLE
Add links to books on bookshelf

### ISSUE THREAD

**Issue by Jacob-Lockwood** [kevinzunigacuellar/web#56]
Hello, just stumbled across your site and was interested in the bookshelf page. Some of the books there look good for me, but I noticed that there are no links to the books on the page. I could just google the title but I'd rather waste a few minutes writing an issue 👍

**Comment by kevinzunigacuellar** [comment]
Hello, thanks for bringing this up. It was an intended decision to avoid referencing book links since everyone has their own preferred bookstores.
