### ISSUE TITLE
Navigator UI moke up

### ISSUE THREAD

**Issue by bruxx-6243** [kevinzunigacuellar/web#98]
Hey @kevinzunigacuellar can you please tell which tool did you use to generate the navigator moke up UI of your site site?

![Navigator screenshot UI](https://user-images.githubusercontent.com/46791833/207947058-9d7c08bf-0ad1-4eb8-a9f8-8105ca0a4814.png)

**Comment by kevinzunigacuellar** [comment]
I used [Microlink](https://microlink.io/)
